name: MurderMystery
version: 1.0.3
api-version: 1.13
author: MCTzOCK
main: net.craftions.murdermystery.Murder
depends: [JenkinsDeploy]
commands:
  start:
    usage: /<command>
  disable-autostart:
    usage: /<command>
  enable-autostart:
    usage: /<command>
